# Generated by Django 5.1.7 on 2025-04-10 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The unique title of the module.', max_length=200, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='If True, the module is accessible to all authenticated users. If False, access is restricted based on ModuleAccess entries.')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('supplementary_title', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Optional field to define the order of content within a module.')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='modules.module')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['module', 'order', 'title'],
                'unique_together': {('module', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SupplementaryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Optional field to define the order of supplementary links.')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_contents', to='modules.content')),
            ],
            options={
                'verbose_name': 'Supplementary Content',
                'verbose_name_plural': 'Supplementary Contents',
                'ordering': ['content', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Einfach', 'Easy'), ('Mittel', 'Medium'), ('Schwer', 'Hard')], default='Mittel', max_length=10)),
                ('hint', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Optional field to define the order of tasks within a module.')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='modules.module')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['module', 'order', 'title'],
                'unique_together': {('module', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when access was granted')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Access Permission',
                'verbose_name_plural': 'Module Access Permissions',
                'ordering': ['user', 'module'],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the task was marked as completed', null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='modules.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Task Progress',
                'verbose_name_plural': 'User Task Progresses',
                'ordering': ['user', 'task'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
