# Generated by Django 5.1.7 on 2025-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_file_path',
            field=models.CharField(blank=True, help_text="Relative path from the 'modules' app directory to the python file containing unittest cases. E.g., 'task_tests/module1/task10_tests.py'", max_length=255),
        ),
    ]
