# Generated by Django 5.1.7 on 2025-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_task_test_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('DevOps & Tools', 'DevOps & Tools'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', help_text='The category this module belongs to.', max_length=50),
        ),
    ]
