# Generated by Django 5.1.7 on 2025-04-22 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0002_task_test_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('duration_weeks', models.PositiveSmallIntegerField(help_text='Bearbeitungszeit ab Start in vollen Wochen.', validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.CharField(choices=[('easy', 'Einfach'), ('medium', 'Mittel'), ('hard', 'Schwer')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modules', models.ManyToManyField(blank=True, help_text='Module, die vor Start dieser Prüfung absolviert sein müssen (optional).', related_name='exams', to='modules.module')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Gestartet'), ('submitted', 'Abgegeben'), ('graded', 'Bewertet')], default='started', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Gesamtpunktzahl (Summe der erreichten Punkte aller Kriterien). Wird automatisch berechnet.', max_digits=7, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='final_exam.exam')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Wer die Bewertung vorgenommen hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exam_uploads/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='final_exam.examattempt')),
            ],
            options={
                'verbose_name': 'Exam Attachment',
                'verbose_name_plural': 'Exam Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('max_points', models.PositiveIntegerField(default=10, help_text='Maximal erreichbare Punktzahl für dieses Kriterium.', validators=[django.core.validators.MinValueValidator(1)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='final_exam.exam')),
            ],
            options={
                'verbose_name': 'Exam Criterion',
                'verbose_name_plural': 'Exam Criteria',
                'ordering': ['exam', 'title'],
                'unique_together': {('exam', 'title')},
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_points', models.DecimalField(decimal_places=2, help_text='Erreichte Punktzahl für dieses Kriterium.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='final_exam.examattempt')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='final_exam.examcriterion')),
            ],
            options={
                'verbose_name': 'Criterion Score',
                'verbose_name_plural': 'Criterion Scores',
                'ordering': ['attempt', 'criterion'],
                'unique_together': {('attempt', 'criterion')},
            },
        ),
    ]
