# Generated by Django 5.1.7 on 2025-04-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_exam', '0002_examrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titel des Zertifikatspfads (z.B. Backend Developer Profi)', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Kurze Beschreibung, was dieser Pfad abdeckt.')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Reihenfolge für die Anzeige (kleinere Zahlen zuerst).')),
                ('icon_name', models.CharField(blank=True, help_text='Name des Icons für das Frontend (z.B. IoCodeSlashOutline).', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exams', models.ManyToManyField(blank=True, help_text='Die Abschlussprüfungen, die Teil dieses Pfades sind.', related_name='certification_paths', to='final_exam.exam')),
            ],
            options={
                'verbose_name': 'Certification Path',
                'verbose_name_plural': 'Certification Paths',
                'ordering': ['order', 'title'],
            },
        ),
    ]
